//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPasteleria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente : Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Pedido = new HashSet<Pedido>();
            this.MediosEnvio = new HashSet<MediosEnvio>();
            this.MediosPago = new HashSet<MediosPago>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string CIUDAD_CLIENTE { get; set; }
        public string DEPARTAMENTO_CLIENTE { get; set; }
        public int TELEFONO_CLIENTE { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediosEnvio> MediosEnvio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediosPago> MediosPago { get; set; }
    }
}
