//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPasteleria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pastel : Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pastel()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int ID_PASTEL { get; set; }
        public string NOMBRE_PASTEL { get; set; }
        public decimal PESO_PASTEL { get; set; }
        public int IDCATEGORIA_PASTEL { get; set; }
        public decimal PRECIO_PASTEL { get; set; }
        public string DESCRIPCION_PASTEL { get; set; }
        public byte[] IMAGEN_PASTEL { get; set; }
        public int ID_CATALOGO { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
