//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPasteleria.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Usuario : Entidad
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDO_USUARIO { get; set; }
        public string CONTRASEÑA_USUARIO { get; set; }
        public string CORREO_ELECTRONICO_USUARIO { get; set; }

        public virtual Administrador Administrador { get; set; }
        public virtual Cliente Cliente { get; set; }

        
    }
       
}
